### ISSUE TITLE
Card art too small and/or inconsistent size.

### ISSUE THREAD

**Issue by matthewrmettler** [matthewrmettler/sundew#4]
I uploaded this deck ( http://netrunnerdb.com/en/decklist/30609/sleepless-i-ll-sleep-when-i-m-dead-# ) and got the following result:

http://i.imgur.com/JwfrOeb.jpg

Ignoring the missing cards ( addressed in issue #3 ), the card art itself is too small, except for the Fausts, which are the correct size. What determines the size of the card art, and how do we fix that?

**Comment by Solarswordsman** [comment]
Just redownloaded wrong images (there were 5 Kappa)
